### ISSUE TITLE
Chromebook Install Error

### ISSUE THREAD

**Issue by mgifford** [A11yWatch/rust-to-npm#1]
~/A11yWatch$ cargo install rust-to-npm
    Updating crates.io index
  Downloaded rust-to-npm v0.3.0
  Downloaded 1 crate (8.2 KB) in 0.73s
  Installing rust-to-npm v0.3.0
  Downloaded bitflags v1.3.2
  Downloaded heck v0.4.0
  Downloaded convert_case v0.5.0
  Downloaded clap_lex v0.2.4
  Downloaded clap v3.2.8
  Downloaded proc-macro2 v1.0.40
  Downloaded strsim v0.10.0
  Downloaded serde v1.0.138
  Downloaded os_str_bytes v6.1.0
  Downloaded proc-macro-error-attr v1.0.4
  Downloaded once_cell v1.13.0
  Downloaded unicode-ident v1.0.1
  Downloaded termcolor v1.1.3
  Downloaded toml v0.5.9
  Downloaded indexmap v1.9.1
  Downloaded clap_derive v3.2.7
  Downloaded hashbrown v0.12.1
  Downloaded serde_derive v1.0.138
  Downloaded atty v0.2.14
  Downloaded proc-macro-error v1.0.4
  Downloaded version_check v0.9.4
  Downloaded quote v1.0.20
  Downloaded textwrap v0.15.0
  Downloaded libc v0.2.126
  Downloaded syn v1.0.98
  Downloaded autocfg v1.1.0
  Downloaded 26 crates (1.8 MB) in 0.43s
   Compiling proc-macro2 v1.0.40
   Compiling unicode-ident v1.0.1
   Compiling quote v1.0.20
   Compiling version_check v0.9.4
   Compiling syn v1.0.98
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `quote` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `proc-macro2` due to previous error
error: could not compile `syn` due to previous error
error: failed to compile `rust-to-npm v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installlWkKEy`

**Comment by j-mendez** [comment]
Hi @mgifford, thanks for the issue. We need `cc` to compile c code. In the vm can you try running `sudo apt install build-essential` first and re-installing? If it solves all of the problems with installs I am fine with this being added to the docs.

**Comment by j-mendez** [comment]
https://github.com/A11yWatch/rust-to-npm/commit/a23c613c15849b8f46a6583f05c078dabd039dec Install instructions for ChromeOS added to the docs. If other issues occur can re-open.
