### ISSUE TITLE
How to deploy to different system targets?

### ISSUE THREAD

**Issue by xorizon** [a11ywatch/rust-to-npm#13]
I wrote a CLI. My npm package works for mac but does not work for Windows.

**Comment by j-mendez** [comment]
Hi @xorizon is there an error message for windows? Thanks!

**Comment by xorizon** [comment]
@j-mendez 
I originally received an error from npm that my package was not public and I could not upload to the registry. To get around it I ran a build and changed the `publishConfig` in package.json to `access: public` and ran `npm publish`. Now that the package is public I was able to run `rust-to-npm-cli deploy -n` and it worked
