### ISSUE TITLE
Consumer requirements | Continuous Integration ?

### ISSUE THREAD

**Issue by melMass** [a11ywatch/rust-to-npm#3]
Hi,

Thanks for this project, I'm looking at the various approaches to embed rust code and I while I want to avoid the blackbox embeded binaries approach, I'm looking for the most transparent solution for the consumers.

Is `rust-to-npm` handling cargo management too or the consumer must install rust/cargo separately?
Sorry if it's obvious but I could not tell for sure from the readme.

Thanks

**Comment by melMass** [comment]
I think this is the sentence that "confuse" me: 
> can be installed on all systems  **by leveraging cargo.**

**Comment by j-mendez** [comment]
@melMass at the moment it installs cargo on the OS if it is missing. Installs are done using crates.io. Going to add a change next version to allow installation from source instead. Npm has the ability to bundle the project “.rs” files so that the installation handling can be done internally instead of the fetch to crates.io.

**Comment by melMass** [comment]
Great!! Thanks, that be perfect to embed the source directly! So it works in CIs?

**Comment by j-mendez** [comment]
> Great!! Thanks, that be perfect to embed the source directly! So it works in CIs?

You are welcome and yes, it can be used to deploy on the CI to crates.io and npm allowing multiple entries to a project.

**Comment by melMass** [comment]
Perfect fit then! Thanks for the quick replies :)

**Comment by j-mendez** [comment]
> Perfect fit then! Thanks for the quick replies :)

Np, including the source released in `v0.4.0` https://github.com/a11ywatch/rust-to-npm/releases/tag/v0.4.0. Thank you for the issue!
