### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by xziy** [a11ywatch/rust-to-npm#4]
rust-to-npm build
Building contents...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: Some(8), col: 0, at: Some(99), message: "missing field `package`", key: [] } }', /home/***/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-to-npm-0.4.1/src/main.rs:92:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by xziy** [comment]
Please close, i forgot add package section
all is ok!

**Comment by j-mendez** [comment]
@xziy no worries!
