### ISSUE TITLE
Install Command with Cargo?

### ISSUE THREAD

**Issue by JimLynchCodes** [a11ywatch/rust-to-npm#6]
I tried `cargo install rust-to-npm-cli` but it gives me this error...

```
Updating crates.io index
error: could not find `rust-to-npm-cli` in registry `crates-io` with version `*`
```

**Comment by j-mendez** [comment]
fixed in latest, accidentally forgot to publish the crate - semi related https://github.com/a11ywatch/rust-to-npm/issues/8.
