### ISSUE TITLE
NPM Install not found

### ISSUE THREAD

**Issue by JimLynchCodes** [a11ywatch/rust-to-npm#7]
Node version: v18.16.0

I run this command:
```
npm i -g rust-to-npm-cli
```

Which outputs:
```
changed 1 package in 759ms
```

But then I try to use it:
```
rust-to-npm build
```

And it says not found...
```
-bash: rust-to-npm: command not found
```

🤔

**Comment by j-mendez** [comment]
Fixed in `v0.4.12`. The refactor on the crate to split into a CLI and rust lib ended up breaking a few things 😅.
Re-run `npm i -g rust-to-npm-cli` to get the latest.

Thanks again!
